import type { Ticket } from "./types";
import { ago } from "./utils";

export const SEED_TICKETS: Ticket[] = [
  {
    id: "t-8842",
    ref: "TK-8842",
    subject: "VPN connection fails on macOS",
    description:
      "VPN client disconnects roughly 30 seconds after connecting on macOS 14. Reproduced on two laptops in the design team.",
    category: "Technical / Network",
    priority: "High",
    status: "In Progress",
    assigneeId: "mk",
    requestedBy: "Alex Rivera",
    createdAt: ago(320),
    updatedAt: ago(45),
    resolvedAt: null,
    history: [
      { id: "h1", at: ago(320), actor: "Alex Rivera", text: "Submitted the request.", kind: "system" },
      { id: "h2", at: ago(300), actor: "Sarah Jenkins", text: "Assigned to Mike Kowalski.", kind: "system" },
      { id: "h3", at: ago(45), actor: "Mike Kowalski", text: "Status changed to In Progress.", kind: "system" },
    ],
  },
  {
    id: "t-8839",
    ref: "TK-8839",
    subject: "Access request for Q3 Payroll folder",
    description: "Need read access to the Q3 Payroll folder to finish the quarterly reconciliation.",
    category: "Permissions / Access",
    priority: "Normal",
    status: "New",
    assigneeId: null,
    requestedBy: "Janice Smith",
    createdAt: ago(140),
    updatedAt: ago(140),
    resolvedAt: null,
    history: [{ id: "h1", at: ago(140), actor: "Janice Smith", text: "Submitted the request.", kind: "system" }],
  },
  {
    id: "t-8838",
    ref: "TK-8838",
    subject: "Payroll system throwing 500 on export",
    description: "Exporting the payroll CSV for finance fails with a server error every time this week.",
    category: "Software / Accounts",
    priority: "Urgent",
    status: "New",
    assigneeId: null,
    requestedBy: "Priya Nair",
    createdAt: ago(60),
    updatedAt: ago(60),
    resolvedAt: null,
    history: [{ id: "h1", at: ago(60), actor: "Priya Nair", text: "Submitted the request.", kind: "system" }],
  },
  {
    id: "t-8835",
    ref: "TK-8835",
    subject: "Monitor flickering when using docking station",
    description: "External monitor flickers every few minutes when connected through the dock.",
    category: "Hardware / IT Support",
    priority: "Normal",
    status: "Pending",
    assigneeId: "sj",
    requestedBy: "Robert Chen",
    createdAt: ago(600),
    updatedAt: ago(200),
    resolvedAt: null,
    history: [
      { id: "h1", at: ago(600), actor: "Robert Chen", text: "Submitted the request.", kind: "system" },
      { id: "h2", at: ago(500), actor: "Sarah Jenkins", text: "Assigned to Sarah Jenkins.", kind: "system" },
      {
        id: "h3",
        at: ago(200),
        actor: "Sarah Jenkins",
        text: "Status changed to Pending — waiting on a replacement dock.",
        kind: "system",
      },
    ],
  },
  {
    id: "t-8830",
    ref: "TK-8830",
    subject: "New starter setup — Priya Nair",
    description: "Laptop, email account, and Slack access needed before Monday.",
    category: "HR / People",
    priority: "High",
    status: "In Progress",
    assigneeId: "ap",
    requestedBy: "Hannah Lowe",
    createdAt: ago(1500),
    updatedAt: ago(320),
    resolvedAt: null,
    history: [
      { id: "h1", at: ago(1500), actor: "Hannah Lowe", text: "Submitted the request.", kind: "system" },
      { id: "h2", at: ago(1400), actor: "Sarah Jenkins", text: "Assigned to Amira Patel.", kind: "system" },
      { id: "h3", at: ago(320), actor: "Amira Patel", text: "Status changed to In Progress.", kind: "system" },
    ],
  },
  {
    id: "t-8826",
    ref: "TK-8826",
    subject: "Printer on 3rd floor jams on double-sided prints",
    description: "Duplex printing jams every time. Single sided works fine.",
    category: "Facilities",
    priority: "Low",
    status: "New",
    assigneeId: null,
    requestedBy: "Tom Barrett",
    createdAt: ago(2600),
    updatedAt: ago(2600),
    resolvedAt: null,
    history: [{ id: "h1", at: ago(2600), actor: "Tom Barrett", text: "Submitted the request.", kind: "system" }],
  },
  {
    id: "t-8821",
    ref: "TK-8821",
    subject: "Figma seat request for two contractors",
    description: "Two editor seats needed for the contract design team until end of quarter.",
    category: "Software / Accounts",
    priority: "Normal",
    status: "Resolved",
    assigneeId: "dw",
    requestedBy: "Maya Foster",
    createdAt: ago(4200),
    updatedAt: ago(900),
    resolvedAt: ago(900),
    history: [
      { id: "h1", at: ago(4200), actor: "Maya Foster", text: "Submitted the request.", kind: "system" },
      { id: "h2", at: ago(4000), actor: "Sarah Jenkins", text: "Assigned to David Wu.", kind: "system" },
      { id: "h3", at: ago(900), actor: "David Wu", text: "Status changed to Resolved — seats provisioned.", kind: "system" },
    ],
  },
  {
    id: "t-8814",
    ref: "TK-8814",
    subject: "Shared drive sync stuck on Windows",
    description: "Sync client reports 'pending' for hours without progress.",
    category: "Technical / Network",
    priority: "Normal",
    status: "Closed",
    assigneeId: "mk",
    requestedBy: "Dana Whitfield",
    createdAt: ago(7000),
    updatedAt: ago(3000),
    resolvedAt: ago(3000),
    history: [
      { id: "h1", at: ago(7000), actor: "Dana Whitfield", text: "Submitted the request.", kind: "system" },
      { id: "h2", at: ago(3000), actor: "Mike Kowalski", text: "Status changed to Closed.", kind: "system" },
    ],
  },
  {
    id: "t-8809",
    ref: "TK-8809",
    subject: "Conference room B screen won't pair",
    description: "Wireless display adapter in room B doesn't show up from any laptop.",
    category: "Facilities",
    priority: "Low",
    status: "Resolved",
    assigneeId: "ap",
    requestedBy: "Leo Martins",
    createdAt: ago(9000),
    updatedAt: ago(8200),
    resolvedAt: ago(8200),
    history: [
      { id: "h1", at: ago(9000), actor: "Leo Martins", text: "Submitted the request.", kind: "system" },
      { id: "h2", at: ago(8200), actor: "Amira Patel", text: "Status changed to Resolved — adapter replaced.", kind: "system" },
    ],
  },
];
